#!/bin/bash
while read -r line
do
	echo "$line" > temp.txt
	gid=$(awk -F ":" '{print $4}' temp.txt)
	groupname_id=$(grep -Fw "$gid" /etc/group | awk -F ":" '{print $1}') 
	username=$(awk -F ":" '{print $1}' temp.txt)
	userid=$(awk -F ":" '{print $3}' temp.txt)
	echo "$username $userid $groupname_id"

	
done < /etc/passwd
rm temp.txt

