#! /bin/bash

FILE=$1
LOG=/var/log/cs183/uptime.log

if [ -e "$FILE" ];
then
	if [ -r "$FILE" ];
        then
		echo "$(date +"%Y-%m-%d %T")- File \"$FILE\" has been found" >> $LOG
	fi
else
	if [ -s "$LOG" ] && [ grep -q "lost" "$LOG" ]; 
	then	
		echo ""	>> $LOG
	else
		echo "$(date +"%Y-%m-%d %T")- File \"$FILE\" has been lost" >> $LOG
	fi
	
fi
